[package]
name = "bank2ledger"
version = "0.1.0"
authors = ["mfkd <mattkfd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
